#!/usr/bin/env bash
# Generates a MYSQL dump and creates a compressed archive out of it
today_dates=$(date + "%d-%m-%Y")
mysqldump -u root -p"$1" --all-database > backup.sql
tar -czvf "$today_date.tar.gz" backup.sql
